### PR TITLE
Fix IP address capture method

### LINKED ISSUE #186: Terraform openstack is not correctly populating /etc/hosts
@join3r @tpouyer 

As per https://github.com/IBM/deploy-ibm-cloud-private/pull/171 it does not work for us with Ubuntu 16.04 on Power. The eth0 interface is UP but with UNKNOWN status.
Better way to handle the code is to get the IP value using hostname -I command. Also, keep it same for both master and worker.

### PR DESCRIPTION
**Pull request by yussufsh**
fixes #186

### CODE REVIEW

**Comment by yussufsh** [comment]
@join3r @tpouyer

**Comment by yussufsh** [comment]
@tpouyer when you have time please review this one.

**Comment by clnperez** [comment]
Isn't this going to put a hostname into your `/etc/hosts` file? And ICP wants to have an IP address there?

**Comment by yussufsh** [comment]
@clnperez yes, this IP variable value is put into /etc/hosts file which is needed by ICP.

**Comment by yussufsh** [comment]
@tpouyer this went in with PR #188. We can close this one.

**Pull request closed without merging**
